//
//  Mathomatic.h
//  Mathomatic
//
//  Created by Mike Griebling on 6 Apr 2015.
//  Copyright (c) 2015 Computer Inspirations. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Matho : NSObject

+ (long) cur_equation;	/* current equation space number (origin 0) */
+ (long) result_en;	/* Equation number of the API's returned result, */
/* if the result is also stored in an equation space, */
/* otherwise -1 for no equation number associated with result. */
/* Set by the last call to matho_parse() or matho_process(). */
/* Useful if you want to know where the result string is from, */
/* to act on it with further commands. */

+ (NSString *)warning_str;	/* optional warning message generated by the last command */

+ (BOOL) init;												/* one-time Mathomatic initialization */
+ (BOOL) process:(NSString *)input toOutput:(NSString **)outputp;	/* Mathomatic command or expression input */
+ (BOOL) parse:(NSString *)input toOutput:(NSString **)outputp;	/* Mathomatic expression or equation input */
+ (void) clear;											/* Restart Mathomatic quickly and cleanly, replaces clear_all(). */

+ (void) free_mem;	/* Free all allocated memory before quitting Mathomatic, if operating system doesn't when done. */
/* Mathomatic becomes unusable after free_mem(), until matho_init() is called again. */
/* Only Symbian OS is known to need a call to free_mem() before quitting. */

+ (BOOL) load_rc:(int) return_true_if_no_file fromFile: (FILE *)ofp;	/* Load Mathomatic startup set options from ~/.mathomaticrc, should allow "set save" to work. */

@end
